port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fake-ip-range: 198.18.0.1/16
proxy-providers:
  Flowercloud:
    type: http
    path: ./Flowercloud.yaml
    url: http://example.com/files/meta1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
  Amy:
    type: http
    path: ./Amy.yaml
    url: http://example.com/files/meta1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
proxies:
  - name: JP
    type: trojan
    server: server
    port: 443
    password: yourpsk
    udp: true
proxy-groups:
  - name: 香港节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)港|hk|hongkong|hong kong"
  - name: 日本节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan"
  - name: 美国节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"
  - name: 狮城节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)新加坡|坡|狮城|SG|Singapore"
  - name: 台湾节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)台|新北|彰化|TW|Taiwan"
  - name: 韩国节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)KR|Korea|KOR|首尔|韩|韓"
  - name: 节点选择
    type: select
    proxies:
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 手动切换
    type: select
    proxies:
      - Flowercloud
      - Amy
      - JP
  - name: 电报消息
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 油管视频
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 奈飞视频
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 巴哈姆特
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 手动切换
      - DRIECT
  - name: EMBY
    type: select
    proxies:
      - 手动切换
      - DRIECT
  - name: PIKPAK
    type: select
    proxies:
      - 手动切换
      - DRIECT
  - name: 哔哩哔哩
    type: select
    proxies:
      - 全球直连
      - 香港节点
      - 台湾节点
  - name: 国外媒体
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 国内媒体
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 游戏平台
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 全球直连
    type: select
    proxies:
      - 节点选择
      - DRIECT
  - name: 广告拦截
    type: select
    proxies:
      - REJECT
      - DRIECT
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
