port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fake-ip-range: 198.18.0.1/16
proxy-providers:
  Flowercloud:
    type: http
    path: ./Flowercloud.yaml
    url: http://example.com/files/meta1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
  Amy:
    type: http
    path: ./Amy.yaml
    url: http://example.com/files/meta1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
proxies:
  - name: JP
    type: trojan
    server: server
    port: 443
    password: yourpsk
    udp: true
proxy-groups:
  - name: 香港节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)港|hk|hongkong|hong kong"
  - name: 日本节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan"
  - name: 美国节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"
  - name: 狮城节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)新加坡|坡|狮城|SG|Singapore"
  - name: 台湾节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)台|新北|彰化|TW|Taiwan"
  - name: 韩国节点
    type: select
    use:
      - Flowercloud
      - Amy
      - JP
    filter: "(?i)KR|Korea|KOR|首尔|韩|韓"
  - name: 节点选择
    type: select
    proxies:
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 手动切换
    type: select
    proxies:
      - Flowercloud
      - Amy
      - JP
  - name: 电报消息
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 油管视频
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 奈飞视频
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 巴哈姆特
    type: select
    proxies:
      - 节点选择
      - 台湾节点
      - 手动切换
      - DRIECT
  - name: Emby
    type: select
    proxies:
      - 手动切换
      - DRIECT
  - name: Pikpak
    type: select
    proxies:
      - 手动切换
      - DRIECT
  - name: 哔哩哔哩
    type: select
    proxies:
      - 全球直连
      - 香港节点
      - 台湾节点
  - name: 国外媒体
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 国内媒体
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 游戏平台
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
  - name: 全球直连
    type: select
    proxies:
      - 节点选择
      - DRIECT
  - name: 广告拦截
    type: select
    proxies:
      - REJECT
      - DRIECT
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DRIECT
rule-providers:
  Netflix:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
    path: ./Netflix.yaml
    interval: 86400
  emby:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Now2happy/listes-1/master/Clash/Ruleset/PlusEmbyDirect.list"
    path: ./emby.yaml
    interval: 86400
  Youtube:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./Youtube.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./Telegram.yaml
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml"
    path: ./Bahamut.yaml
    interval: 86400
  Bilibili:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./Bilibili.yaml
    interval: 86400
  Game:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml"
    path: ./Game.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./Microsoft.yaml
    interval: 86400
  Apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.yaml"
    path: ./Apple.yaml
    interval: 86400
  pikpak:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml"
    path: ./pikpak.yaml
    interval: 86400
  ChinaMedia:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml"
    path: ./ChinaMedia.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml"
    path: ./GlobalMedia.yaml
    interval: 86400
  China:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Domain.yaml"
    path: ./China.yaml
    interval: 86400
  Global:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.yaml"
    path: ./Global.yaml
    interval: 86400
  ADblock:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml"
    path: ./ADblock.yaml
    interval: 86400
rules:
  - RULE-SET,Netflix,奈飞视频
  - RULE-SET,emby,Emby
  - RULE-SET,Youtube,油管视频
  - RULE-SET,Telegram,电报消息
  - RULE-SET,Bahamut,巴哈姆特
  - RULE-SET,Bilibili,哔哩哔哩
  - RULE-SET,Game,游戏平台
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,Apple,苹果服务
  - RULE-SET,pikpak,Pikpak
  - RULE-SET,ChinaMedia,国内媒体
  - RULE-SET,GlobalMedia,国外媒体
  - RULE-SET,China,全球直连
  - RULE-SET,Global,节点选择
  - RULE-SET,ADblock,广告拦截
  - GEOIP,,全球直连
  - GEOIP,CN,全球直连
  - MATCH,漏网之鱼
