port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
ipv6: false
hosts: null
dns:
    enable: true
    ipv6: false
    listen: '0.0.0.0:1053'
    use-hosts: true
    default-nameserver: [119.29.29.29, 8.8.8.8, 1.1.1.1]
    nameserver: [223.5.5.5, 119.29.29.29]
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['*.lan', '*.localdomain', '*.example', '*.invalid', '*.localhost', '*.test', '*.local', '*.home.arpa', 'time.*.com', 'time.*.gov', 'time.*.edu.cn', 'time.*.apple.com', 'time1.*.com', 'time2.*.com', 'time3.*.com', 'time4.*.com', 'time5.*.com', 'time6.*.com', 'time7.*.com', 'ntp.*.com', 'ntp1.*.com', 'ntp2.*.com', 'ntp3.*.com', 'ntp4.*.com', 'ntp5.*.com', 'ntp6.*.com', 'ntp7.*.com', '*.time.edu.cn', '*.ntp.org.cn', +.pool.ntp.org, time1.cloud.tencent.com, 'stun.*.*', 'stun.*.*.*', swscan.apple.com, mesu.apple.com, music.163.com, '*.music.163.com', '*.126.net', musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, '*.kuwo.cn', api-jooxtt.sanook.com, api.joox.com, y.qq.com, '*.y.qq.com', streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, localhost.ptlogin2.qq.com, '*.msftconnecttest.com', '*.msftncsi.com', '*.xiami.com', '*.music.migu.cn', music.migu.cn, +.wotgame.cn, +.wggames.cn, +.wowsgame.cn, +.wargaming.net, '*.*.*.srv.nintendo.net', '*.*.stun.playstation.net', 'xbox.*.*.microsoft.com', '*.*.xboxlive.com', '*.ipv6.microsoft.com', 'teredo.*.*.*', 'teredo.*.*', speedtest.cros.wr.pvp.net, +.jjvip8.com, www.douyu.com, activityapi.huya.com, activityapi.huya.com.w.cdngslb.com, www.bilibili.com, api.bilibili.com, a.w.bilicdn1.com]
external-controller: '127.0.0.1:9090'
clash-for-android:
    append-system-dns: false
proxy-providers:  
  Flowercloud:
    type: http
    path: ./Flowercloud.yaml
    url: https://api.huacloud.xyz/sub?target=clash&insert=true&emoji=true&udp=true&clash.doh=true&new_name=true&filename=Flower_SS&url=https%3A%2F%2Fapi.flowercloud.xyz%2Fosubscribe.php%3Fsid%3D8165%26token%3DRqLyLqUa0pwM%26sip002%3D1
    interval: 86400
  Amy:
    type: http
    path: ./Amy.yaml
    url: https://orxyji.xyz/?L1N1YnNjcmlwdGlvbi9DbGFzaD9zaWQ9Mzk5MDImdG9rZW49OE5LNEZSeFZ5YU4mbW09NDk5ODgmOWFhZTJhZTE2MTdmNDQ4MGI4Njc1OGNlNDlmNQ==
    interval: 86400
proxies:
  - name: JP
    type: trojan
    server: nenkada.buzz
    port: 443
    password: 2669086
    udp: true
proxy-groups:
  - name: 香港节点
    type: select
    use:
      - Flowercloud
      - Amy
    filter: "(?i)港|hk|hongkong|hong kong"
  - name: 日本节点
    type: select
    use:
      - Flowercloud
      - Amy
    proxies:
      - JP
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan"
  - name: 美国节点
    type: select
    use:
      - Flowercloud
      - Amy
    filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"
  - name: 狮城节点
    type: select
    use:
      - Flowercloud
      - Amy
    filter: "(?i)新加坡|坡|狮城|SG|Singapore"
  - name: 台湾节点
    type: select
    use:
      - Flowercloud
      - Amy
    filter: "(?i)台|新北|彰化|TW|Taiwan"
  - name: 韩国节点
    type: select
    use:
      - Flowercloud
      - Amy
    filter: "(?i)KR|Korea|KOR|首尔|韩|韓"
  - name: 节点选择
    type: select
    proxies:
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 手动切换
    type: select
    use:
      - Flowercloud
      - Amy
    proxies:
      - JP
  - name: 电报消息
    type: select
    proxies:
      - 手动切换
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - DIRECT
  - name: 油管视频
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 奈飞视频
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 巴哈姆特
    type: select
    proxies:
      - 台湾节点
      - 节点选择
      - 手动切换
      - DIRECT
  - name: Emby
    type: select
    proxies:
      - 手动切换
      - DIRECT
  - name: Pikpak
    type: select
    proxies:
      - DIRECT
      - 手动切换
  - name: 哔哩哔哩
    type: select
    proxies:
      - DIRECT
      - 香港节点
      - 台湾节点
  - name: 国外媒体
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
  - name: 国内媒体
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
  - name: 微软服务
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
  - name: 苹果服务
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
  - name: 游戏平台
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
  - name: 全球直连
    type: select
    proxies:
      - DIRECT
      - 节点选择
  - name: 广告拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - 香港节点
      - 台湾节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 韩国节点
      - 手动切换
      - DIRECT
rule-providers:
  Netflix:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
    path: ./Netflix.yaml
    interval: 86400
  emby:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    path: ./emby.yaml
    interval: 86400
  Youtube:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
    path: ./Youtube.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    path: ./Telegram.yaml
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml
    path: ./Bahamut.yaml
    interval: 86400
  Bilibili:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml
    path: ./Bilibili.yaml
    interval: 86400
  Game:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
    path: ./Game.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./Microsoft.yaml
    interval: 86400
  Apple:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.yaml
    path: ./Apple.yaml
    interval: 86400
  pikpak:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml
    path: ./pikpak.yaml
    interval: 86400
  ChinaMedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml
    path: ./ChinaMedia.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml
    path: ./GlobalMedia.yaml
    interval: 86400
  China:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Domain.yaml
    path: ./China.yaml
    interval: 86400
  Global:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.yaml
    path: ./Global.yaml
    interval: 86400
  ADblock:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Domain.yaml
    path: ./ADblock.yaml
    interval: 86400
rules:
  - RULE-SET,Netflix,奈飞视频
  - RULE-SET,emby,Emby
  - RULE-SET,Youtube,油管视频
  - RULE-SET,Telegram,电报消息
  - RULE-SET,Bahamut,巴哈姆特
  - RULE-SET,Bilibili,哔哩哔哩
  - RULE-SET,Game,游戏平台
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,Apple,苹果服务
  - RULE-SET,pikpak,Pikpak
  - RULE-SET,ChinaMedia,国内媒体
  - RULE-SET,GlobalMedia,国外媒体
  - RULE-SET,China,全球直连
  - RULE-SET,Global,节点选择
  - RULE-SET,ADblock,广告拦截
  - GEOIP,,全球直连
  - GEOIP,CN,全球直连
  - MATCH,漏网之鱼
